#!/usr/bin/env bash
# Usage: de c
# Summary: Launches Rails console

if test -f ./script/console; then
  echo 'Starting console...' && ./script/console;
elif test -f Gemfile; then
  echo 'Starting console...' && bundle exec rails c;
else
  echo "Seems it's not a Rails project"
fi