#!/usr/bin/env ruby

require "yaml"

config_path = File.expand_path("~/.ssh/config")

puts "Generating SSH config file (#{config_path})..."

File.open(config_path, "w+") do |config|
  Dir[File.expand_path("~/.ssh/hosts/**/*.yml")].sort.each do |file|
    hosts = YAML.load(File.read(file))

    hosts.each_pair do |key, settings|
      config.puts "host #{key}"

      settings.each_pair do |key, value|
        config.puts "  #{key} #{value}" unless key == 'de'
      end

      config.puts
    end

    config.puts
  end
end

puts "Done!"