#!/usr/bin/env ruby

system %{mkdir -p tmp}

if ARGV.include?('clean')
  puts "Cleaning caches..."

  system %{rm -rf public/assets/* tmp/cache/*}
end

flags = []

if ARGV.include?('offline')
  puts 'Running offline...'

  flags << "OFFLINE=true"
end

existing = `pgrep -f 'nginx.*master'`.strip

if existing.size > 0
  puts "Stopping currently running server..."

  system %{sudo kill #{existing}}
end

puts "Starting server..."

system %{#{flags.join(' ')} passenger start --max-pool-size=2}

