#!/usr/bin/env ruby
# Provide de completions
# Usage: de stl <server>
# Summary: Connects to specified remote server & tails production.log

require File.expand_path('../lib/ssh_hosts', __FILE__)

if ARGV.first == '--complete'
  SshHosts.host_list_autocomplete
else
  server = ARGV.first

  rails_folder = SshHosts.remote_rails_folder(server)

  puts "Connecting..."

  SshHosts.remote_command(server, %{
    tail -n 500 -f #{ rails_folder }/shared/log/production.log
  })
end
